CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  username VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50),
  able_to_add_rival BOOLEAN,
  profile_image VARCHAR(255),
  pomodoro_enabled BOOLEAN,
  pomodoro_study_minute INTEGER,
  pomodoro_break_minute INTEGER,
  major VARCHAR(50)
);

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);
