package com.process.clash.domain.common.enums;

public enum GoodsActingCategory {
    PURCHASE,
    SEASON_REWARD,
    ROADMAP_V2_CHAPTER_REWARD,
    ROADMAP_V2_SECTION_REWARD,
    BATTLE_WIN_REWARD,
    BATTLE_LOSE_REWARD,
    BATTLE_DRAW_REWARD,
    ATTENDANCE_DAILY_REWARD,
    ATTENDANCE_WEEKLY_REWARD
}
