CREATE TABLE user_equipped_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMPTZ                            NOT NULL,
    updated_at    TIMESTAMPTZ                            NOT NULL,
    fk_user_id    BIGINT                                 NOT NULL,
    fk_product_id BIGINT                                 NOT NULL,
    category      VARCHAR(255)                           NOT NULL,
    CONSTRAINT pk_user_equipped_items PRIMARY KEY (id),
    CONSTRAINT uc_user_equipped_items_user_category UNIQUE (fk_user_id, category),
    CONSTRAINT ck_user_equipped_items_category
        CHECK (category IN ('INSIGNIA', 'NAMEPLATE', 'BANNER'))
);

ALTER TABLE user_equipped_items
    ADD CONSTRAINT fk_user_equipped_items_on_fk_user
        FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE user_equipped_items
    ADD CONSTRAINT fk_user_equipped_items_on_fk_product
        FOREIGN KEY (fk_product_id) REFERENCES products (id);

CREATE INDEX idx_user_equipped_items_user_id
    ON user_equipped_items (fk_user_id);
