CREATE TABLE auth_events
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(255)                            NOT NULL,
    event_type  VARCHAR(255)                            NOT NULL,
    ip_address  VARCHAR(255),
    device      VARCHAR(255),
    occurred_at TIMESTAMPTZ             NOT NULL,
    CONSTRAINT pk_auth_events PRIMARY KEY (id)
);

CREATE TABLE battles
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMPTZ             NOT NULL,
    updated_at    TIMESTAMPTZ             NOT NULL,
    start_date    date                                    NOT NULL,
    end_date      date                                    NOT NULL,
    battle_status VARCHAR(255)                            NOT NULL,
    fk_winner_id  BIGINT,
    fk_rival_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_battles PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMPTZ             NOT NULL,
    updated_at TIMESTAMPTZ             NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE chapters
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    section_id  BIGINT,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    order_index INTEGER                                 NOT NULL,
    created_at  TIMESTAMPTZ             NOT NULL,
    updated_at  TIMESTAMPTZ             NOT NULL,
    CONSTRAINT pk_chapters PRIMARY KEY (id)
);

CREATE TABLE chapters_v2
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_section_id      BIGINT                                  NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    description        VARCHAR(255),
    order_index        INTEGER                                 NOT NULL,
    study_material_url VARCHAR(500),
    created_at         TIMESTAMPTZ             NOT NULL,
    updated_at         TIMESTAMPTZ             NOT NULL,
    CONSTRAINT pk_chapters_v2 PRIMARY KEY (id)
);

CREATE TABLE choices
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_id BIGINT,
    content     VARCHAR(255)                            NOT NULL,
    is_correct  BOOLEAN                                 NOT NULL,
    order_index INTEGER                                 NOT NULL,
    created_at  TIMESTAMPTZ             NOT NULL,
    updated_at  TIMESTAMPTZ             NOT NULL,
    CONSTRAINT pk_choices PRIMARY KEY (id)
);

CREATE TABLE choices_v2
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_question_id BIGINT                                  NOT NULL,
    content        VARCHAR(255)                            NOT NULL,
    is_correct     BOOLEAN                                 NOT NULL,
    order_index    INTEGER                                 NOT NULL,
    created_at     TIMESTAMPTZ             NOT NULL,
    updated_at     TIMESTAMPTZ             NOT NULL,
    CONSTRAINT pk_choices_v2 PRIMARY KEY (id)
);

CREATE TABLE github_daily_stats
(
    user_id      BIGINT  NOT NULL,
    study_date   date    NOT NULL,
    commit_count INTEGER NOT NULL,
    pr_count     INTEGER NOT NULL,
    issue_count  INTEGER NOT NULL,
    review_count INTEGER NOT NULL,
    additions    BIGINT  NOT NULL,
    deletions    BIGINT  NOT NULL,
    synced_at    TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_github_daily_stats PRIMARY KEY (user_id, study_date)
);

CREATE TABLE group_members
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_group_id BIGINT                                  NOT NULL,
    fk_user_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_group_members PRIMARY KEY (id)
);

CREATE TABLE groups
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMPTZ             NOT NULL,
    updated_at        TIMESTAMPTZ             NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    description       VARCHAR(255)                            NOT NULL,
    max_members       INTEGER                                 NOT NULL,
    password          VARCHAR(255),
    password_required BOOLEAN                                 NOT NULL,
    category          VARCHAR(255)                            NOT NULL,
    fk_user_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

CREATE TABLE major_questions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMPTZ             NOT NULL,
    updated_at TIMESTAMPTZ             NOT NULL,
    web        INTEGER,
    app        INTEGER,
    server     INTEGER,
    ai         INTEGER,
    game       INTEGER,
    CONSTRAINT pk_major_questions PRIMARY KEY (id)
);

CREATE TABLE mission_questions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_mission_id BIGINT                                  NOT NULL,
    content       VARCHAR(1000)                           NOT NULL,
    explanation   VARCHAR(255),
    order_index   INTEGER                                 NOT NULL,
    created_at    TIMESTAMPTZ             NOT NULL,
    updated_at    TIMESTAMPTZ             NOT NULL,
    CONSTRAINT pk_mission_questions PRIMARY KEY (id)
);

CREATE TABLE missions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_chapter_id BIGINT                                  NOT NULL,
    title         VARCHAR(255)                            NOT NULL,
    difficulty    INTEGER                                 NOT NULL,
    order_index   INTEGER                                 NOT NULL,
    created_at    TIMESTAMPTZ             NOT NULL,
    updated_at    TIMESTAMPTZ             NOT NULL,
    CONSTRAINT pk_missions PRIMARY KEY (id)
);

CREATE TABLE products
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMPTZ             NOT NULL,
    updated_at   TIMESTAMPTZ             NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    category     VARCHAR(255),
    image        VARCHAR(255)                            NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    price        BIGINT                                  NOT NULL,
    discount     INTEGER                                 NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    popularity   BIGINT                                  NOT NULL,
    fk_season_id BIGINT,
    is_seasonal  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE purchases
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMPTZ             NOT NULL,
    updated_at    TIMESTAMPTZ             NOT NULL,
    goods_type    VARCHAR(255)                            NOT NULL,
    price         BIGINT                                  NOT NULL,
    fk_product_id BIGINT                                  NOT NULL,
    fk_user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_purchases PRIMARY KEY (id)
);

CREATE TABLE questions_v2
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_chapter_id BIGINT                                  NOT NULL,
    content       VARCHAR(1000)                           NOT NULL,
    explanation   VARCHAR(255),
    order_index   INTEGER                                 NOT NULL,
    difficulty    INTEGER                                 NOT NULL,
    created_at    TIMESTAMPTZ             NOT NULL,
    updated_at    TIMESTAMPTZ             NOT NULL,
    CONSTRAINT pk_questions_v2 PRIMARY KEY (id)
);

CREATE TABLE recommended_products
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMPTZ             NOT NULL,
    updated_at    TIMESTAMPTZ             NOT NULL,
    fk_product_id BIGINT                                  NOT NULL,
    display_order INTEGER                                 NOT NULL,
    start_date    date                                    NOT NULL,
    end_date      date                                    NOT NULL,
    is_active     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_recommended_products PRIMARY KEY (id)
);

CREATE TABLE rivals
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_first_user_id     BIGINT                                  NOT NULL,
    fk_second_user_id    BIGINT                                  NOT NULL,
    rival_linking_status VARCHAR(255)                            NOT NULL,
    created_at           TIMESTAMPTZ             NOT NULL,
    updated_at           TIMESTAMPTZ             NOT NULL,
    CONSTRAINT pk_rivals PRIMARY KEY (id)
);

CREATE TABLE seasons
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ             NOT NULL,
    updated_at TIMESTAMPTZ             NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    start_date date                                    NOT NULL,
    end_date   date                                    NOT NULL,
    CONSTRAINT pk_seasons PRIMARY KEY (id)
);

CREATE TABLE section_key_points
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_section_id BIGINT                                  NOT NULL,
    content       VARCHAR(255),
    order_index   INTEGER                                 NOT NULL,
    created_at    TIMESTAMPTZ             NOT NULL,
    updated_at    TIMESTAMPTZ             NOT NULL,
    CONSTRAINT pk_section_key_points PRIMARY KEY (id)
);

CREATE TABLE section_prerequisites
(
    prerequisite_id BIGINT NOT NULL,
    section_id      BIGINT NOT NULL,
    CONSTRAINT pk_section_prerequisites PRIMARY KEY (prerequisite_id, section_id)
);

CREATE TABLE sections
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    major       VARCHAR(255)                            NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    category_id BIGINT                                  NOT NULL,
    order_index INTEGER                                 NOT NULL,
    created_at  TIMESTAMPTZ             NOT NULL,
    updated_at  TIMESTAMPTZ             NOT NULL,
    CONSTRAINT pk_sections PRIMARY KEY (id)
);

CREATE TABLE study_sessions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fk_user_id  BIGINT                                  NOT NULL,
    fk_task_id  BIGINT,
    record_type VARCHAR(20)                             NOT NULL,
    app_name    VARCHAR(255),
    started_at  TIMESTAMPTZ             NOT NULL,
    ended_at    TIMESTAMPTZ,
    CONSTRAINT pk_study_sessions PRIMARY KEY (id),
    CONSTRAINT ck_study_sessions_record_type
        CHECK (record_type IN ('TASK', 'ACTIVITY')),
    CONSTRAINT ck_study_sessions_record_payload
        CHECK (
            (record_type = 'TASK' AND fk_task_id IS NOT NULL AND app_name IS NULL)
                OR
            (record_type = 'ACTIVITY' AND fk_task_id IS NULL AND app_name IS NOT NULL)
        )
);

CREATE TABLE record_activity_segments
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fk_study_session_id BIGINT                                  NOT NULL,
    app_name            VARCHAR(255)                            NOT NULL,
    started_at          TIMESTAMPTZ             NOT NULL,
    ended_at            TIMESTAMPTZ,
    CONSTRAINT pk_record_activity_segments PRIMARY KEY (id),
    CONSTRAINT ck_record_activity_segments_time_range
        CHECK (ended_at IS NULL OR ended_at > started_at)
);

CREATE TABLE tasks
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ             NOT NULL,
    updated_at TIMESTAMPTZ             NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    fk_user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

CREATE TABLE user_exp_history
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMPTZ             NOT NULL,
    date            date                                    NOT NULL,
    earn_exp        INTEGER                                 NOT NULL,
    acting_category VARCHAR(255)                            NOT NULL,
    fk_user_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_exp_history PRIMARY KEY (id)
);

CREATE TABLE user_github
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    git_hub_id          VARCHAR(255)                            NOT NULL,
    github_user_node_id VARCHAR(255),
    github_emails       VARCHAR(2000),
    github_access_token VARCHAR(255),
    fk_user_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_github PRIMARY KEY (id)
);

CREATE TABLE user_goods_history
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMPTZ             NOT NULL,
    goods_type            VARCHAR(255)                            NOT NULL,
    goods_acting_category VARCHAR(255)                            NOT NULL,
    variation             INTEGER                                 NOT NULL,
    fk_product_id         BIGINT,
    fk_user_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_goods_history PRIMARY KEY (id)
);

CREATE TABLE user_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMPTZ             NOT NULL,
    updated_at    TIMESTAMPTZ             NOT NULL,
    fk_user_id    BIGINT                                  NOT NULL,
    fk_product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_items PRIMARY KEY (id)
);

CREATE TABLE user_mission_history
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_user_id             BIGINT                                  NOT NULL,
    fk_mission_id          BIGINT                                  NOT NULL,
    is_cleared             BOOLEAN                                 NOT NULL,
    correct_count          INTEGER                                 NOT NULL,
    total_count            INTEGER                                 NOT NULL,
    current_question_index INTEGER,
    created_at             TIMESTAMPTZ             NOT NULL,
    updated_at             TIMESTAMPTZ             NOT NULL,
    CONSTRAINT pk_user_mission_history PRIMARY KEY (id)
);

CREATE TABLE user_notices
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMPTZ             NOT NULL,
    updated_at      TIMESTAMPTZ             NOT NULL,
    notice_category VARCHAR(255)                            NOT NULL,
    is_read         BOOLEAN                                 NOT NULL,
    fk_sender_id    BIGINT                                  NOT NULL,
    fk_receiver_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_notices PRIMARY KEY (id)
);

CREATE TABLE user_pomodoro_setting
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMPTZ             NOT NULL,
    updated_at            TIMESTAMPTZ             NOT NULL,
    pomodoro_enabled      BOOLEAN                                 NOT NULL,
    pomodoro_study_minute INTEGER                                 NOT NULL,
    pomodoro_break_minute INTEGER                                 NOT NULL,
    fk_user_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_pomodoro_setting PRIMARY KEY (id)
);

CREATE TABLE user_question_history_v2
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_user_id             BIGINT                                  NOT NULL,
    fk_chapter_id          BIGINT                                  NOT NULL,
    is_cleared             BOOLEAN                                 NOT NULL,
    correct_count          INTEGER                                 NOT NULL,
    total_count            INTEGER                                 NOT NULL,
    current_question_index INTEGER,
    created_at             TIMESTAMPTZ             NOT NULL,
    updated_at             TIMESTAMPTZ             NOT NULL,
    CONSTRAINT pk_user_question_history_v2 PRIMARY KEY (id)
);

CREATE TABLE user_rank_history
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMPTZ             NOT NULL,
    date         date                                    NOT NULL,
    rank         INTEGER                                 NOT NULL,
    exp_tier     VARCHAR(255)                            NOT NULL,
    rank_tier    VARCHAR(255)                            NOT NULL,
    fk_user_id   BIGINT                                  NOT NULL,
    fk_season_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_rank_history PRIMARY KEY (id)
);

CREATE TABLE user_section_progress
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_user_id            BIGINT                                  NOT NULL,
    fk_section_id         BIGINT                                  NOT NULL,
    fk_current_chapter_id BIGINT,
    completed_chapters    INTEGER                                 NOT NULL,
    is_completed          BOOLEAN                                 NOT NULL,
    created_at            TIMESTAMPTZ             NOT NULL,
    updated_at            TIMESTAMPTZ             NOT NULL,
    CONSTRAINT pk_user_section_progress PRIMARY KEY (id)
);

CREATE TABLE user_study_times
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date                     date                                    NOT NULL,
    total_study_time_seconds BIGINT                                  NOT NULL,
    fk_user_id               BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_study_times PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMPTZ             NOT NULL,
    updated_at    TIMESTAMPTZ             NOT NULL,
    username      VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    role          VARCHAR(255)                            NOT NULL,
    profile_image VARCHAR(255),
    total_exp     INTEGER                                 NOT NULL,
    total_cookie  INTEGER                                 NOT NULL,
    total_token   INTEGER                                 NOT NULL,
    major         VARCHAR(255),
    user_status   VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE user_items
    ADD CONSTRAINT uc_51663cd0d2fd28adb9044c4cf UNIQUE (fk_user_id, fk_product_id);

ALTER TABLE purchases
    ADD CONSTRAINT uc_5677307ad2f56344d49b3542b UNIQUE (fk_user_id, fk_product_id);

ALTER TABLE user_section_progress
    ADD CONSTRAINT uc_677d128308b3a20a068a5697b UNIQUE (fk_user_id, fk_section_id);

ALTER TABLE user_study_times
    ADD CONSTRAINT uc_c95eb0d2f159b79f151d97cab UNIQUE (fk_user_id, date);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_name UNIQUE (name);

ALTER TABLE user_mission_history
    ADD CONSTRAINT uc_dcf5d2b81ef33bff0d500c29d UNIQUE (fk_user_id, fk_mission_id);

ALTER TABLE group_members
    ADD CONSTRAINT uc_df5f40f984676cb0ecc370d85 UNIQUE (fk_group_id, fk_user_id);

ALTER TABLE user_question_history_v2
    ADD CONSTRAINT uc_fab34e4974c5c6cff15a144ae UNIQUE (fk_user_id, fk_chapter_id);

ALTER TABLE seasons
    ADD CONSTRAINT uc_seasons_name UNIQUE (name);

ALTER TABLE user_github
    ADD CONSTRAINT uc_user_github_fk_user UNIQUE (fk_user_id);

ALTER TABLE user_github
    ADD CONSTRAINT uc_user_github_githubid UNIQUE (git_hub_id);

ALTER TABLE user_pomodoro_setting
    ADD CONSTRAINT uc_user_pomodoro_setting_fk_user UNIQUE (fk_user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE github_daily_stats
    ADD CONSTRAINT uq_github_daily_stats_user_date UNIQUE (user_id, study_date);

ALTER TABLE battles
    ADD CONSTRAINT FK_BATTLES_ON_FK_RIVAL FOREIGN KEY (fk_rival_id) REFERENCES rivals (id);

ALTER TABLE battles
    ADD CONSTRAINT FK_BATTLES_ON_FK_WINNER FOREIGN KEY (fk_winner_id) REFERENCES users (id);

ALTER TABLE chapters
    ADD CONSTRAINT FK_CHAPTERS_ON_SECTION FOREIGN KEY (section_id) REFERENCES sections (id);

ALTER TABLE chapters_v2
    ADD CONSTRAINT FK_CHAPTERS_V2_ON_FK_SECTION FOREIGN KEY (fk_section_id) REFERENCES sections (id);

ALTER TABLE choices
    ADD CONSTRAINT FK_CHOICES_ON_QUESTION FOREIGN KEY (question_id) REFERENCES mission_questions (id);

ALTER TABLE choices_v2
    ADD CONSTRAINT FK_CHOICES_V2_ON_FK_QUESTION FOREIGN KEY (fk_question_id) REFERENCES questions_v2 (id);

ALTER TABLE groups
    ADD CONSTRAINT FK_GROUPS_ON_FK_USER FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE group_members
    ADD CONSTRAINT FK_GROUP_MEMBERS_ON_FK_GROUP FOREIGN KEY (fk_group_id) REFERENCES groups (id);

ALTER TABLE group_members
    ADD CONSTRAINT FK_GROUP_MEMBERS_ON_FK_USER FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE missions
    ADD CONSTRAINT FK_MISSIONS_ON_FK_CHAPTER FOREIGN KEY (fk_chapter_id) REFERENCES chapters (id);

ALTER TABLE mission_questions
    ADD CONSTRAINT FK_MISSION_QUESTIONS_ON_FK_MISSION FOREIGN KEY (fk_mission_id) REFERENCES missions (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_FK_SEASON FOREIGN KEY (fk_season_id) REFERENCES seasons (id);

ALTER TABLE purchases
    ADD CONSTRAINT FK_PURCHASES_ON_FK_PRODUCT FOREIGN KEY (fk_product_id) REFERENCES products (id);

ALTER TABLE purchases
    ADD CONSTRAINT FK_PURCHASES_ON_FK_USER FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE questions_v2
    ADD CONSTRAINT FK_QUESTIONS_V2_ON_FK_CHAPTER FOREIGN KEY (fk_chapter_id) REFERENCES chapters_v2 (id);

ALTER TABLE recommended_products
    ADD CONSTRAINT FK_RECOMMENDED_PRODUCTS_ON_FK_PRODUCT FOREIGN KEY (fk_product_id) REFERENCES products (id);

ALTER TABLE record_activity_segments
    ADD CONSTRAINT fk_record_activity_segments_study_session
        FOREIGN KEY (fk_study_session_id) REFERENCES study_sessions (id);

ALTER TABLE rivals
    ADD CONSTRAINT FK_RIVALS_ON_FK_FIRST_USER FOREIGN KEY (fk_first_user_id) REFERENCES users (id);

ALTER TABLE rivals
    ADD CONSTRAINT FK_RIVALS_ON_FK_SECOND_USER FOREIGN KEY (fk_second_user_id) REFERENCES users (id);

ALTER TABLE sections
    ADD CONSTRAINT FK_SECTIONS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE section_key_points
    ADD CONSTRAINT FK_SECTION_KEY_POINTS_ON_FK_SECTION FOREIGN KEY (fk_section_id) REFERENCES sections (id);

ALTER TABLE study_sessions
    ADD CONSTRAINT FK_STUDY_SESSIONS_ON_FK_TASK FOREIGN KEY (fk_task_id) REFERENCES tasks (id);

ALTER TABLE study_sessions
    ADD CONSTRAINT FK_STUDY_SESSIONS_ON_FK_USER FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_FK_USER FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE user_exp_history
    ADD CONSTRAINT FK_USER_EXP_HISTORY_ON_FK_USER FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE user_github
    ADD CONSTRAINT FK_USER_GITHUB_ON_FK_USER FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE user_goods_history
    ADD CONSTRAINT FK_USER_GOODS_HISTORY_ON_FK_PRODUCT FOREIGN KEY (fk_product_id) REFERENCES products (id);

ALTER TABLE user_goods_history
    ADD CONSTRAINT FK_USER_GOODS_HISTORY_ON_FK_USER FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE user_items
    ADD CONSTRAINT FK_USER_ITEMS_ON_FK_PRODUCT FOREIGN KEY (fk_product_id) REFERENCES products (id);

ALTER TABLE user_items
    ADD CONSTRAINT FK_USER_ITEMS_ON_FK_USER FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE user_mission_history
    ADD CONSTRAINT FK_USER_MISSION_HISTORY_ON_FK_MISSION FOREIGN KEY (fk_mission_id) REFERENCES missions (id);

ALTER TABLE user_mission_history
    ADD CONSTRAINT FK_USER_MISSION_HISTORY_ON_FK_USER FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE user_notices
    ADD CONSTRAINT FK_USER_NOTICES_ON_FK_RECEIVER FOREIGN KEY (fk_receiver_id) REFERENCES users (id);

ALTER TABLE user_notices
    ADD CONSTRAINT FK_USER_NOTICES_ON_FK_SENDER FOREIGN KEY (fk_sender_id) REFERENCES users (id);

ALTER TABLE user_pomodoro_setting
    ADD CONSTRAINT FK_USER_POMODORO_SETTING_ON_FK_USER FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE user_question_history_v2
    ADD CONSTRAINT FK_USER_QUESTION_HISTORY_V2_ON_FK_CHAPTER FOREIGN KEY (fk_chapter_id) REFERENCES chapters_v2 (id);

ALTER TABLE user_question_history_v2
    ADD CONSTRAINT FK_USER_QUESTION_HISTORY_V2_ON_FK_USER FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE user_rank_history
    ADD CONSTRAINT FK_USER_RANK_HISTORY_ON_FK_SEASON FOREIGN KEY (fk_season_id) REFERENCES seasons (id);

ALTER TABLE user_rank_history
    ADD CONSTRAINT FK_USER_RANK_HISTORY_ON_FK_USER FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE user_section_progress
    ADD CONSTRAINT FK_USER_SECTION_PROGRESS_ON_FK_CURRENT_CHAPTER FOREIGN KEY (fk_current_chapter_id) REFERENCES chapters (id);

ALTER TABLE user_section_progress
    ADD CONSTRAINT FK_USER_SECTION_PROGRESS_ON_FK_SECTION FOREIGN KEY (fk_section_id) REFERENCES sections (id);

ALTER TABLE user_section_progress
    ADD CONSTRAINT FK_USER_SECTION_PROGRESS_ON_FK_USER FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE user_study_times
    ADD CONSTRAINT FK_USER_STUDY_TIMES_ON_FK_USER FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE section_prerequisites
    ADD CONSTRAINT fk_secpre_on_prerequisite FOREIGN KEY (prerequisite_id) REFERENCES sections (id);

ALTER TABLE section_prerequisites
    ADD CONSTRAINT fk_secpre_on_section FOREIGN KEY (section_id) REFERENCES sections (id);

CREATE UNIQUE INDEX uk_study_sessions_active_user
    ON study_sessions (fk_user_id)
    WHERE ended_at IS NULL;

CREATE UNIQUE INDEX uk_record_activity_segments_open_session
    ON record_activity_segments (fk_study_session_id)
    WHERE ended_at IS NULL;

CREATE OR REPLACE FUNCTION set_updated_at_utc()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_study_sessions_set_updated_at
    BEFORE UPDATE
    ON study_sessions
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at_utc();

CREATE TRIGGER trg_record_activity_segments_set_updated_at
    BEFORE UPDATE
    ON record_activity_segments
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at_utc();
