CREATE SEQUENCE IF NOT EXISTS auth_events_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS battles_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS categories_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS chapters_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS choices_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS group_members_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS groups_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS major_questions_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS mission_questions_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS missions_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS products_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS recommended_products_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS rivals_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS seasons_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS section_key_points_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS sections_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS study_sessions_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS tasks_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_exp_history_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_github_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_goods_history_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_mission_history_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_notices_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_pomodoro_setting_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_rank_history_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_section_progress_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_study_times_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE auth_events
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    device      VARCHAR(255),
    event_type  VARCHAR(255)                            NOT NULL,
    ip_address  VARCHAR(255),
    occurred_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    username    VARCHAR(255)                            NOT NULL,
    CONSTRAINT auth_events_pkey PRIMARY KEY (id)
);

CREATE TABLE battles
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    battle_status VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date      date                                    NOT NULL,
    start_date    date                                    NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fk_rival_id   BIGINT                                  NOT NULL,
    fk_winner_id  BIGINT,
    CONSTRAINT battles_pkey PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id)
);

CREATE TABLE chapters
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description VARCHAR(255),
    order_index INTEGER                                 NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    section_id  BIGINT,
    CONSTRAINT chapters_pkey PRIMARY KEY (id)
);

CREATE TABLE choices
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content     VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_correct  BOOLEAN                                 NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    question_id BIGINT,
    CONSTRAINT choices_pkey PRIMARY KEY (id)
);

CREATE TABLE github_daily_stats
(
    study_date   date                        NOT NULL,
    user_id      BIGINT                      NOT NULL,
    additions    BIGINT                      NOT NULL,
    commit_count INTEGER                     NOT NULL,
    deletions    BIGINT                      NOT NULL,
    issue_count  INTEGER                     NOT NULL,
    pr_count     INTEGER                     NOT NULL,
    review_count INTEGER                     NOT NULL,
    synced_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uq_github_daily_stats_user_date PRIMARY KEY (study_date, user_id)
);

CREATE TABLE group_members
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_group_id BIGINT                                  NOT NULL,
    fk_user_id  BIGINT                                  NOT NULL,
    CONSTRAINT group_members_pkey PRIMARY KEY (id)
);

CREATE TABLE groups
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category          VARCHAR(255)                            NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description       VARCHAR(255)                            NOT NULL,
    max_members       INTEGER                                 NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    password          VARCHAR(255),
    password_required BOOLEAN                                 NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fk_user_id        BIGINT                                  NOT NULL,
    CONSTRAINT groups_pkey PRIMARY KEY (id)
);

CREATE TABLE major_questions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    ai         INTEGER,
    app        INTEGER,
    game       INTEGER,
    server     INTEGER,
    web        INTEGER,
    CONSTRAINT major_questions_pkey PRIMARY KEY (id)
);

CREATE TABLE mission_questions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content       VARCHAR(1000)                           NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    explanation   VARCHAR(255),
    order_index   INTEGER                                 NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fk_mission_id BIGINT                                  NOT NULL,
    CONSTRAINT mission_questions_pkey PRIMARY KEY (id)
);

CREATE TABLE missions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    difficulty    INTEGER                                 NOT NULL,
    order_index   INTEGER                                 NOT NULL,
    title         VARCHAR(255)                            NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fk_chapter_id BIGINT                                  NOT NULL,
    CONSTRAINT missions_pkey PRIMARY KEY (id)
);

CREATE TABLE products
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category     VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    discount     INTEGER                                 NOT NULL,
    image        VARCHAR(255)                            NOT NULL,
    is_seasonal  BOOLEAN                                 NOT NULL,
    popularity   BIGINT                                  NOT NULL,
    price        BIGINT                                  NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fk_season_id BIGINT,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE recommended_products
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    display_order INTEGER                                 NOT NULL,
    end_date      date                                    NOT NULL,
    is_active     BOOLEAN                                 NOT NULL,
    start_date    date                                    NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fk_product_id BIGINT                                  NOT NULL,
    CONSTRAINT recommended_products_pkey PRIMARY KEY (id)
);

CREATE TABLE rivals
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    rival_linking_status VARCHAR(255)                            NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fk_first_user_id     BIGINT                                  NOT NULL,
    fk_second_user_id    BIGINT                                  NOT NULL,
    CONSTRAINT rivals_pkey PRIMARY KEY (id)
);

CREATE TABLE seasons
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   date                                    NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    start_date date                                    NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT seasons_pkey PRIMARY KEY (id)
);

CREATE TABLE section_key_points
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content       VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    order_index   INTEGER                                 NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fk_section_id BIGINT                                  NOT NULL,
    CONSTRAINT section_key_points_pkey PRIMARY KEY (id)
);

CREATE TABLE section_prerequisites
(
    section_id      BIGINT NOT NULL,
    prerequisite_id BIGINT NOT NULL,
    CONSTRAINT section_prerequisites_pkey PRIMARY KEY (section_id, prerequisite_id)
);

CREATE TABLE sections
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description VARCHAR(255),
    major       VARCHAR(255)                            NOT NULL,
    order_index INTEGER                                 NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    category_id BIGINT                                  NOT NULL,
    CONSTRAINT sections_pkey PRIMARY KEY (id)
);

CREATE TABLE study_sessions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    ended_at   TIMESTAMP WITHOUT TIME ZONE,
    started_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fk_task_id BIGINT                                  NOT NULL,
    fk_user_id BIGINT                                  NOT NULL,
    CONSTRAINT study_sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE tasks
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fk_user_id BIGINT                                  NOT NULL,
    CONSTRAINT tasks_pkey PRIMARY KEY (id)
);

CREATE TABLE user_exp_history
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    acting_category VARCHAR(255)                            NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    date            date                                    NOT NULL,
    earn_exp        INTEGER                                 NOT NULL,
    fk_user_id      BIGINT                                  NOT NULL,
    CONSTRAINT user_exp_history_pkey PRIMARY KEY (id)
);

CREATE TABLE user_github
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    git_hub_id          VARCHAR(255)                            NOT NULL,
    github_access_token VARCHAR(255),
    github_emails       VARCHAR(2000),
    github_user_node_id VARCHAR(255),
    fk_user_id          BIGINT                                  NOT NULL,
    CONSTRAINT user_github_pkey PRIMARY KEY (id)
);

CREATE TABLE user_goods_history
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    goods_acting_category VARCHAR(255)                            NOT NULL,
    goods_type            VARCHAR(255)                            NOT NULL,
    variation             INTEGER                                 NOT NULL,
    fk_product_id         BIGINT,
    fk_user_id            BIGINT                                  NOT NULL,
    CONSTRAINT user_goods_history_pkey PRIMARY KEY (id)
);

CREATE TABLE user_mission_history
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    correct_count          INTEGER                                 NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    current_question_index INTEGER,
    is_cleared             BOOLEAN                                 NOT NULL,
    total_count            INTEGER                                 NOT NULL,
    updated_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fk_mission_id          BIGINT                                  NOT NULL,
    fk_user_id             BIGINT                                  NOT NULL,
    CONSTRAINT user_mission_history_pkey PRIMARY KEY (id)
);

CREATE TABLE user_notices
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_read         BOOLEAN                                 NOT NULL,
    notice_category VARCHAR(255)                            NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fk_receiver_id  BIGINT                                  NOT NULL,
    fk_sender_id    BIGINT                                  NOT NULL,
    CONSTRAINT user_notices_pkey PRIMARY KEY (id)
);

CREATE TABLE user_pomodoro_setting
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    pomodoro_break_minute INTEGER                                 NOT NULL,
    pomodoro_enabled      BOOLEAN                                 NOT NULL,
    pomodoro_study_minute INTEGER                                 NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fk_user_id            BIGINT                                  NOT NULL,
    CONSTRAINT user_pomodoro_setting_pkey PRIMARY KEY (id)
);

CREATE TABLE user_rank_history
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    date         date                                    NOT NULL,
    exp_tier     VARCHAR(255)                            NOT NULL,
    rank         INTEGER                                 NOT NULL,
    rank_tier    VARCHAR(255)                            NOT NULL,
    fk_season_id BIGINT                                  NOT NULL,
    fk_user_id   BIGINT                                  NOT NULL,
    CONSTRAINT user_rank_history_pkey PRIMARY KEY (id)
);

CREATE TABLE user_section_progress
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    completed_chapters    INTEGER                                 NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_completed          BOOLEAN                                 NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fk_current_chapter_id BIGINT,
    fk_section_id         BIGINT                                  NOT NULL,
    fk_user_id            BIGINT                                  NOT NULL,
    CONSTRAINT user_section_progress_pkey PRIMARY KEY (id)
);

CREATE TABLE user_study_times
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date                     date                                    NOT NULL,
    total_study_time_seconds BIGINT                                  NOT NULL,
    fk_user_id               BIGINT                                  NOT NULL,
    CONSTRAINT user_study_times_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    major         VARCHAR(255),
    name          VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    profile_image VARCHAR(255),
    role          VARCHAR(255)                            NOT NULL,
    total_cookie  INTEGER                                 NOT NULL,
    total_exp     INTEGER                                 NOT NULL,
    total_token   INTEGER                                 NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_status   VARCHAR(255),
    username      VARCHAR(255)                            NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE user_section_progress
    ADD CONSTRAINT uka5od2tvg7oyebxylyj7t44hph UNIQUE (fk_user_id, fk_section_id);

ALTER TABLE seasons
    ADD CONSTRAINT ukdxjxuegifna4w15f9k83uvr32 UNIQUE (name);

ALTER TABLE user_mission_history
    ADD CONSTRAINT ukgkcoa63uwe4yxf3wgbqge3v90 UNIQUE (fk_user_id, fk_mission_id);

ALTER TABLE user_pomodoro_setting
    ADD CONSTRAINT ukh2d9eyc2s1ixxu34g80txd3w8 UNIQUE (fk_user_id);

ALTER TABLE user_github
    ADD CONSTRAINT ukh31udrpgqi6bls507aayxlj0w UNIQUE (git_hub_id);

ALTER TABLE group_members
    ADD CONSTRAINT ukid3t9yn8p1vqpakeoplbjkueu UNIQUE (fk_group_id, fk_user_id);

ALTER TABLE user_study_times
    ADD CONSTRAINT ukm9fm55b2he52bi9k5if8j4jc6 UNIQUE (fk_user_id, date);

ALTER TABLE user_github
    ADD CONSTRAINT ukosny9v3bru687h1v97mmhib6i UNIQUE (fk_user_id);

ALTER TABLE users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);

ALTER TABLE categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);

ALTER TABLE sections
    ADD CONSTRAINT fk15bmqnobtsj3orniaen9e94jl FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE NO ACTION;

ALTER TABLE study_sessions
    ADD CONSTRAINT fk1x8qp3510leyjlgkab7qauua1 FOREIGN KEY (fk_task_id) REFERENCES tasks (id) ON DELETE NO ACTION;

ALTER TABLE user_goods_history
    ADD CONSTRAINT fk2porv2ri2tvo9vcuuxh08abpj FOREIGN KEY (fk_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE mission_questions
    ADD CONSTRAINT fk37tj047s4x8v7yl20vrr3wncf FOREIGN KEY (fk_mission_id) REFERENCES missions (id) ON DELETE NO ACTION;

ALTER TABLE missions
    ADD CONSTRAINT fk3lwq9lsioida85xl1u8kx1ymv FOREIGN KEY (fk_chapter_id) REFERENCES chapters (id) ON DELETE NO ACTION;

ALTER TABLE study_sessions
    ADD CONSTRAINT fk48g0nkvd13u7phov98oby5c0b FOREIGN KEY (fk_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE user_notices
    ADD CONSTRAINT fk4j1s1rtm35o01diqvjjjxqhs1 FOREIGN KEY (fk_receiver_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE group_members
    ADD CONSTRAINT fk6ingx9cv2rrx82jdan819xvk4 FOREIGN KEY (fk_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE user_github
    ADD CONSTRAINT fk7hop9h26rnug68jd94tknwuge FOREIGN KEY (fk_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE products
    ADD CONSTRAINT fk7un2ii3isaw0rhfmnj5njfvo3 FOREIGN KEY (fk_season_id) REFERENCES seasons (id) ON DELETE NO ACTION;

ALTER TABLE rivals
    ADD CONSTRAINT fk9ojtpmlf0k4jql3136sxs7as9 FOREIGN KEY (fk_second_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE groups
    ADD CONSTRAINT fka6a2owuddmyu0pouxe5v5gv4a FOREIGN KEY (fk_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE user_section_progress
    ADD CONSTRAINT fkabb2b3707j67dy93snc44w5jd FOREIGN KEY (fk_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE user_goods_history
    ADD CONSTRAINT fkafoecjl0lllcobcwbj3m7fac6 FOREIGN KEY (fk_product_id) REFERENCES products (id) ON DELETE NO ACTION;

ALTER TABLE user_mission_history
    ADD CONSTRAINT fkah09ywyyaxvb49arl1xgr9fx3 FOREIGN KEY (fk_mission_id) REFERENCES missions (id) ON DELETE NO ACTION;

ALTER TABLE user_mission_history
    ADD CONSTRAINT fkcf7gqhsq60o4ilt3qh7f72owj FOREIGN KEY (fk_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE user_rank_history
    ADD CONSTRAINT fkf18ehguiu7pohjf8j5gk954ig FOREIGN KEY (fk_season_id) REFERENCES seasons (id) ON DELETE NO ACTION;

ALTER TABLE group_members
    ADD CONSTRAINT fkhvr6sbxm4viajxhco8rq5nunt FOREIGN KEY (fk_group_id) REFERENCES groups (id) ON DELETE NO ACTION;

ALTER TABLE battles
    ADD CONSTRAINT fkiimgo6qq4w3ckgbti29ktg7cj FOREIGN KEY (fk_winner_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE battles
    ADD CONSTRAINT fkj0c8x0u557q1ly5x9wahaf2nl FOREIGN KEY (fk_rival_id) REFERENCES rivals (id) ON DELETE NO ACTION;

ALTER TABLE section_prerequisites
    ADD CONSTRAINT fkj7epwn3pby30h0yl361c1v6af FOREIGN KEY (prerequisite_id) REFERENCES sections (id) ON DELETE NO ACTION;

ALTER TABLE section_key_points
    ADD CONSTRAINT fklbe647gptf5f0dl70cxt645q9 FOREIGN KEY (fk_section_id) REFERENCES sections (id) ON DELETE NO ACTION;

ALTER TABLE user_pomodoro_setting
    ADD CONSTRAINT fko2h2bk89fc2d9qf8sb57phfjr FOREIGN KEY (fk_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE user_exp_history
    ADD CONSTRAINT fko4ds1eur0abcgj6wowuk4ol76 FOREIGN KEY (fk_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE recommended_products
    ADD CONSTRAINT fkogp6hdtankr5sopg9jgko2041 FOREIGN KEY (fk_product_id) REFERENCES products (id) ON DELETE NO ACTION;

ALTER TABLE user_rank_history
    ADD CONSTRAINT fkok9k3kd83iui42t1cme9lj39u FOREIGN KEY (fk_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE user_section_progress
    ADD CONSTRAINT fkpbsnkwc3cb86fkm810obletqa FOREIGN KEY (fk_current_chapter_id) REFERENCES chapters (id) ON DELETE NO ACTION;

ALTER TABLE rivals
    ADD CONSTRAINT fkpwe2b9bqc758bsyrb5e3mpucp FOREIGN KEY (fk_first_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE choices
    ADD CONSTRAINT fkpwhwwfash3xplc3dtdxxsk9gq FOREIGN KEY (question_id) REFERENCES mission_questions (id) ON DELETE NO ACTION;

ALTER TABLE user_notices
    ADD CONSTRAINT fkr003a445f2c7w1hvp7lv7wgly FOREIGN KEY (fk_sender_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE chapters
    ADD CONSTRAINT fkrmak30ej6dm0i4m55vohe2hti FOREIGN KEY (section_id) REFERENCES sections (id) ON DELETE NO ACTION;

ALTER TABLE tasks
    ADD CONSTRAINT fkrpwjdidf6uq2mvuvrv66ybo3o FOREIGN KEY (fk_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE user_section_progress
    ADD CONSTRAINT fktg265puyo8qrexpb9ck7dwx69 FOREIGN KEY (fk_section_id) REFERENCES sections (id) ON DELETE NO ACTION;

ALTER TABLE user_study_times
    ADD CONSTRAINT fktlugjt6on1nplxb80pjj11qc4 FOREIGN KEY (fk_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE section_prerequisites
    ADD CONSTRAINT fktmwu3p32gffiffjqyk5ccl23n FOREIGN KEY (section_id) REFERENCES sections (id) ON DELETE NO ACTION;