CREATE TABLE announcements
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ                             NOT NULL,
    updated_at TIMESTAMPTZ                             NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    author     VARCHAR(255)                            NOT NULL DEFAULT 'PROCESS',
    user_id    BIGINT,
    content    TEXT                                    NOT NULL,
    start_at   TIMESTAMPTZ                             NOT NULL,
    end_at     TIMESTAMPTZ                             NOT NULL,
    hideable   BOOLEAN                                 NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_announcements PRIMARY KEY (id)
);
