CREATE TABLE user_attendances
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMPTZ                             NOT NULL,
    updated_at      TIMESTAMPTZ                             NOT NULL,
    fk_user_id      BIGINT                                  NOT NULL,
    attendance_date DATE                                    NOT NULL,
    is_attended     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_user_attendances PRIMARY KEY (id),
    CONSTRAINT uc_user_attendances_user_date UNIQUE (fk_user_id, attendance_date)
);

ALTER TABLE user_attendances
    ADD CONSTRAINT fk_user_attendances_on_fk_user
        FOREIGN KEY (fk_user_id) REFERENCES users (id);

CREATE INDEX idx_user_attendances_user_id
    ON user_attendances (fk_user_id);