CREATE TABLE record_activity_segments
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fk_study_session_id BIGINT                                  NOT NULL,
    app_name            VARCHAR(255)                            NOT NULL,
    started_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    ended_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_record_activity_segments PRIMARY KEY (id)
);

ALTER TABLE record_activity_segments
    ADD CONSTRAINT fk_record_activity_segments_study_session
        FOREIGN KEY (fk_study_session_id)
            REFERENCES study_sessions (id);

ALTER TABLE record_activity_segments
    ADD CONSTRAINT ck_record_activity_segments_time_range
        CHECK (ended_at IS NULL OR ended_at > started_at);

INSERT INTO record_activity_segments (
    fk_study_session_id,
    app_name,
    started_at,
    ended_at,
    created_at,
    updated_at
)
SELECT
    s.id,
    s.app_name,
    s.started_at,
    s.ended_at,
    NOW(),
    NOW()
FROM study_sessions s
WHERE s.record_type = 'ACTIVITY'
  AND s.app_name IS NOT NULL;

CREATE UNIQUE INDEX uk_study_sessions_active_user
    ON study_sessions (fk_user_id)
    WHERE ended_at IS NULL;

CREATE UNIQUE INDEX uk_record_activity_segments_open_session
    ON record_activity_segments (fk_study_session_id)
    WHERE ended_at IS NULL;
