CREATE TABLE record_subjects_v2
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name       VARCHAR(255)                            NOT NULL,
    fk_user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_record_subjects_v2 PRIMARY KEY (id)
);

CREATE TABLE record_tasks_v2
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name                 VARCHAR(255)                            NOT NULL,
    fk_record_subject_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_record_tasks_v2 PRIMARY KEY (id)
);

CREATE TABLE record_active_sessions_v2
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fk_user_id   BIGINT                                  NOT NULL,
    session_type VARCHAR(20)                             NOT NULL,
    started_at   TIMESTAMPTZ             NOT NULL,
    ended_at     TIMESTAMPTZ,
    CONSTRAINT pk_record_active_sessions_v2 PRIMARY KEY (id),
    CONSTRAINT ck_record_active_sessions_v2_session_type
        CHECK (session_type IN ('DEVELOP', 'TASK')),
    CONSTRAINT ck_record_active_sessions_v2_time_range
        CHECK (ended_at IS NULL OR ended_at > started_at)
);

CREATE TABLE record_develop_sessions_v2
(
    id     BIGINT      NOT NULL,
    app_id VARCHAR(50) NOT NULL,
    CONSTRAINT pk_record_develop_sessions_v2 PRIMARY KEY (id),
    CONSTRAINT ck_record_develop_sessions_v2_app_id
        CHECK (app_id IN ('VSCODE', 'WEBSTORM', 'INTELLIJ_IDEA', 'PYCHARM', 'GOLAND', 'PHPSTORM', 'RUBYMINE', 'CLION', 'RIDER', 'ANDROID_STUDIO', 'XCODE'))
);

CREATE TABLE record_task_sessions_v2
(
    id                   BIGINT NOT NULL,
    fk_record_subject_id BIGINT NOT NULL,
    fk_record_task_id    BIGINT,
    CONSTRAINT pk_record_task_sessions_v2 PRIMARY KEY (id)
);

CREATE TABLE record_develop_session_segments_v2
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                   TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                   TIMESTAMPTZ             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fk_record_develop_session_id BIGINT                                  NOT NULL,
    app_id                       VARCHAR(50)                             NOT NULL,
    started_at                   TIMESTAMPTZ             NOT NULL,
    ended_at                     TIMESTAMPTZ,
    CONSTRAINT pk_record_develop_session_segments_v2 PRIMARY KEY (id),
    CONSTRAINT ck_record_develop_session_segments_v2_app_id
        CHECK (app_id IN ('VSCODE', 'WEBSTORM', 'INTELLIJ_IDEA', 'PYCHARM', 'GOLAND', 'PHPSTORM', 'RUBYMINE', 'CLION', 'RIDER', 'ANDROID_STUDIO', 'XCODE')),
    CONSTRAINT ck_record_develop_session_segments_v2_time_range
        CHECK (ended_at IS NULL OR ended_at > started_at)
);

ALTER TABLE record_subjects_v2
    ADD CONSTRAINT fk_record_subjects_v2_user
        FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE record_tasks_v2
    ADD CONSTRAINT fk_record_tasks_v2_subject
        FOREIGN KEY (fk_record_subject_id) REFERENCES record_subjects_v2 (id);

ALTER TABLE record_active_sessions_v2
    ADD CONSTRAINT fk_record_active_sessions_v2_user
        FOREIGN KEY (fk_user_id) REFERENCES users (id);

ALTER TABLE record_develop_sessions_v2
    ADD CONSTRAINT fk_record_develop_sessions_v2_active_session
        FOREIGN KEY (id) REFERENCES record_active_sessions_v2 (id);

ALTER TABLE record_task_sessions_v2
    ADD CONSTRAINT fk_record_task_sessions_v2_active_session
        FOREIGN KEY (id) REFERENCES record_active_sessions_v2 (id);

ALTER TABLE record_task_sessions_v2
    ADD CONSTRAINT fk_record_task_sessions_v2_subject
        FOREIGN KEY (fk_record_subject_id) REFERENCES record_subjects_v2 (id);

ALTER TABLE record_task_sessions_v2
    ADD CONSTRAINT fk_record_task_sessions_v2_task
        FOREIGN KEY (fk_record_task_id) REFERENCES record_tasks_v2 (id);

ALTER TABLE record_develop_session_segments_v2
    ADD CONSTRAINT fk_record_develop_session_segments_v2_develop_session
        FOREIGN KEY (fk_record_develop_session_id) REFERENCES record_develop_sessions_v2 (id);

CREATE UNIQUE INDEX uk_record_active_sessions_v2_active_user
    ON record_active_sessions_v2 (fk_user_id)
    WHERE ended_at IS NULL;

CREATE UNIQUE INDEX uk_record_develop_segments_v2_open_session
    ON record_develop_session_segments_v2 (fk_record_develop_session_id)
    WHERE ended_at IS NULL;

CREATE INDEX idx_record_task_sessions_v2_subject_id
    ON record_task_sessions_v2 (fk_record_subject_id);

CREATE INDEX idx_record_task_sessions_v2_task_id
    ON record_task_sessions_v2 (fk_record_task_id);

CREATE INDEX idx_record_tasks_v2_subject_id
    ON record_tasks_v2 (fk_record_subject_id);

CREATE TRIGGER trg_record_subjects_v2_set_updated_at
    BEFORE UPDATE
    ON record_subjects_v2
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at_utc();

CREATE TRIGGER trg_record_tasks_v2_set_updated_at
    BEFORE UPDATE
    ON record_tasks_v2
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at_utc();

CREATE TRIGGER trg_record_active_sessions_v2_set_updated_at
    BEFORE UPDATE
    ON record_active_sessions_v2
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at_utc();

CREATE TRIGGER trg_record_develop_session_segments_v2_set_updated_at
    BEFORE UPDATE
    ON record_develop_session_segments_v2
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at_utc();
